#!/bin/bash
echo "IP" 
ifconfig |grep inet
echo "ssh"
systemctl status sshd |grep Active
echo "tftp"
systemctl status tftp |grep Active
echo "dhcpd"
systemctl status dhcpd |grep Active
echo "puppet server"
systemctl status puppetmaster |grep Active
echo "puppet agent"
systemctl status puppet |grep Active
echo chronyd
systemctl status chronyd |grep Active
echo OpenLava
systemctl status openlava|grep Active
#systemctl status sshd
#systemctl status sshd
