#!/bin/bash
echo "IP" 
ifconfig |grep inet
echo "Ssh"
systemctl status sshd |grep Active
echo "Tftp"
systemctl status tftp |grep Active
echo "Dhcpd"
systemctl status dhcpd |grep Active
echo "Puppet server"
systemctl status puppetmaster |grep Active
echo "Puppet agent"
systemctl status puppet |grep Active
echo "Chronyd"
systemctl status chronyd |grep Active
echo "OpenLava"
systemctl status openlava|grep Active
#systemctl status sshd
#systemctl status sshd
