#!/bin/bash
################################
### DON'T LEAVE ANY OTHER CONFIG FILES IN 
### /ETC/SYSCONFIG/NETWORK-SCRIPTS THEN THOSE WHICH HAVE TO BE THERE!!! 
### NO BACKUPS ARE ALOWED !!!
###############################
yum -y install dhcp

echo "# dhcpd.conf
option domain-name "kdlabs.uel.ac.uk";
option domain-name-servers 192.168.1.243;
default-lease-time 432000;
max-lease-time 432000;
authoritative;
subnet 192.168.1.0 netmask 255.255.255.0 {
  range 192.168.1.1 192.168.1.242;
  option domain-name-servers cluster-master.kdlabs.uel.ac.uk;
  option domain-name "kdlabs.uel.ac.uk";
  option routers 192.168.1.243;
  option broadcast-address 192.168.1.255;
next-server 192.168.1.243;
	filename "pxelinux.0";
	default-lease-time 432000;
	max-lease-time 432000;
}
" > /etc/dhcp/dhcpd.conf

systemctl start dhcpd
systemctl enable dhcpd

yum install xinetd syslinux tftp-server

#https://jablonskis.org/2011/howto-to-build-a-diskless-linux-cluster/index.html

echo "service tftp
{
        socket_type             = dgram
        protocol                = udp
        wait                    = yes
        user                    = root
        server                  = /usr/sbin/in.tftpd
        server_args             = -s /tftpboot -v
        disable                 = no
        per_source              = 11
        cps                     = 100 2
        flags                   = IPv4
}" > /etc/xinetd.d/tftp

service xinetd start && chkconfig xinetd on

echo "[Unit]
Description=Tftp Server
Requires=tftp.socket
Documentation=man:in.tftpd

[Service]
ExecStart=/usr/sbin/in.tftpd -c -s /tftpboot
StandardInput=socket

[Install]
WantedBy=multi-user.target
Also=tftp.socket
" > /usr/lib/systemd/system/tftp.service

echo "# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=permissive
# SELINUXTYPE= can take one of three two values:
#     targeted - Targeted processes are protected,
#     minimum - Modification of targeted policy. Only selected processes are pr$
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted" > /etc/selinux/config

#init 6

sestatus

#After running sestatus you should see this below

#SELinux status:                 enabled
#SELinuxfs mount:                /sys/fs/selinux
#SELinux root directory:         /etc/selinux
#Loaded policy name:             targeted
#Current mode:                   permissive
#Mode from config file:          permissive
#Policy MLS status:              enabled
#Policy deny_unknown status:     allowed
#Max kernel policy version:      28

getsebool -a|grep tftp

#After running getsebool command you should see this
#tftp_anon_write --> off
#tftp_home_dir --> off

setsebool -P tftp_anon_write 1
setsebool -P tftp_home_dir 1

firewall-cmd --permanent --zone=public --add-service=tftp
firewall-cmd --reload

####### might be mess
#echo "-A INPUT -m state --state NEW -m udp -p udp -m udp --dport 69 -j ACCEPT" > /etc/sysconfig/iptables
firewall-cmd --zone=public --add-service=tftp --permanent
firewall-cmd --reload
###################################
systemctl status firewalld
systemctl enable firewalld
systemctl start firewalld

#PXE
# create directories required for pxe bootloader

mkdir -p /tftpboot/{linux,pxelinux.cfg}

# copy pxe boot loader (comes with syslinux package)
cp /usr/share/syslinux/pxelinux.0 /tftpboot/

#download kernel

cd /tftboot
wget -P /tftpboot/centos7/ \
http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/vmlinuz \
http://mirror.centos.org/centos/7/os/x86_64/images/pxeboot/initrd.img

echo "
# boots a linux kernel and mounts nfs file system as a root file system

label   node
        kernel centos7/vmlinuz
        append initrd=centos7/initrd.img root=nfs:192.168.1.243:/tftpboot/centos7/root rw selinux=0
" > /tftpboot/pxelinux.cfg/C0A8

#C0A8 is equvivalet to 192.168
