#!/bin/bash

ssh-keygen -t rsa

#copy /root/.ssh/id_rsa.pub to other nodes

http://www.openlava.org/tarball/openlava-2.2.tar.gz

tar -xvzf openlava-2.2.tar.gz
cd openlava-2.2
yum install -y gcc tcl tcl-devel ncurses-devel


./configure
make install

cd config
cp lsb.hosts lsb.params lsb.queues lsb.users lsf.cluster.openlava lsf.conf lsf.shared lsf.tasks openlava.* /opt/openlava-2.2/etc

#nano /opt/openlava-2.2/etc/lsf.cluster.openlava

echo "#-----------------------------------------------------------------------
   # T H I S   I S   A    O N E   P E R   C L U S T E R    F I L E
   #
   # This is a sample cluster definition file.  There is a cluster
   # definition file for each cluster.  This file's name should be
   # lsf.cluster..
   # See lsf.cluster(5) and the "LSF Administrator's Guide".
   #

   Begin   ClusterAdmins
   Administrators = openlava
   End    ClusterAdmins

   Begin   Host
   HOSTNAME          model          type  server  r1m  RESOURCES
   claster-master      !              !     1       -       -
   End     Host

   Begin ResourceMap
   RESOURCENAME  LOCATION
   # tmp2          [default]
   # nio           [all]
   # console       [default]
   End ResourceMap" > /opt/openlava-2.2/etc/lsf.cluster.openlava

useradd -r openlava
chown -R openlava:openlava /opt/openlava-2.2 

cp /opt/openlava-2.2/etc/openlava /etc/init.d
chkconfig openlava on
cp /opt/openlava-2.2/etc/openlava.* /etc/profile.d
service openlava start

#just for checking
lsid
lsload
bhosts
bqueues
bsub 'echo my first job;sleep 60'

#check for result of your job
#cat /var/spool/mail/lubo
#or install alpine to get CLI GUI to check your results

yum -y install alpine

