#!/bin/bash
echo "IP" 
ifconfig |grep inet
echo "ssh"
#systemctl restart sshd |grep Active
echo "tftp"
#systemctl restart tftp |grep Active
echo "dhcpd"
systemctl restart dhcpd |grep Active
echo "puppet server"
#systemctl restart puppetmaster |grep Active
echo "puppet agent"
#systemctl restart puppet |grep Active
#systemctl status sshd
#systemctl status sshd
